<?php

declare(strict_types=1);

use Sumire\Connection;
use Sumire\EntityManager;
use Sumire\Tests\Fixtures\User;

require __DIR__ . '/../vendor/autoload.php';

function assert_true(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

$driver = getenv('SUMIRE_DRIVER') ?: '';
$dsn = getenv('SUMIRE_DSN') ?: '';
$dbUser = getenv('SUMIRE_USER') ?: null;
$password = getenv('SUMIRE_PASSWORD') ?: null;

if (!in_array($driver, ['mysql', 'pgsql'], true) || $dsn === '') {
    fwrite(STDERR, "Set SUMIRE_DRIVER=mysql|pgsql, SUMIRE_DSN, SUMIRE_USER, and SUMIRE_PASSWORD.\n");
    exit(2);
}

$pdo = new PDO($dsn, $dbUser, $password);
$connection = new Connection($pdo);
$entityManager = new EntityManager($connection);

$connection->execute('DROP TABLE IF EXISTS users');

if ($driver === 'pgsql') {
    $connection->execute(<<<'SQL'
        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            active BOOLEAN NOT NULL
        )
        SQL);
} else {
    $connection->execute(<<<'SQL'
        CREATE TABLE users (
            id BIGINT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            active BOOLEAN NOT NULL
        )
        SQL);
}

$repository = $entityManager->repository(User::class);

$user = new User('Ada Lovelace', 'ada.integration@example.com');
$entityManager->persist($user);

assert_true($user->id() === 1, sprintf('%s should assign generated id.', $driver));

$found = $repository->find($user->id());

assert_true($found instanceof User, sprintf('%s should find inserted user.', $driver));
assert_true($found->active() === true, sprintf('%s should hydrate true boolean.', $driver));

$found->deactivate();
$entityManager->persist($found);

$inactive = $repository->firstBy(['active' => false]);

assert_true($inactive instanceof User, sprintf('%s should query false boolean criteria.', $driver));
assert_true($inactive->active() === false, sprintf('%s should hydrate false boolean.', $driver));

$entityManager->remove($inactive);

assert_true($repository->find($user->id()) === null, sprintf('%s should remove entity.', $driver));

echo sprintf("%s integration test passed.\n", $driver);
