<?php

declare(strict_types=1);

namespace Sumire\Schema;

use BackedEnum;
use DateTimeInterface;
use ReflectionEnum;
use ReflectionNamedType;
use Sumire\ColumnType;
use Sumire\Connection;
use Sumire\Exception\MappingException;
use Sumire\Exception\SumireException;
use Sumire\Mapping\EntityMetadata;
use Sumire\Mapping\MetadataFactory;
use Sumire\Mapping\PropertyMapping;

final readonly class SchemaManager
{
    public function __construct(
        private Connection $connection,
        private MetadataFactory $metadataFactory,
    ) {}

    /** @param class-string $entityClass */
    public function createTable(string $entityClass, bool $ifNotExists = false): void
    {
        $metadata = $this->metadataFactory->for($entityClass);
        $driver = $this->connection->driverName();

        $this->assertSupportedDriver($driver);

        $columns = array_map(
            fn(PropertyMapping $mapping): string => $this->columnDefinition($metadata, $mapping, $driver),
            $metadata->properties(),
        );

        $sql = sprintf(
            "CREATE TABLE%s %s (\n    %s\n)",
            $ifNotExists ? ' IF NOT EXISTS' : '',
            $this->connection->quoteIdentifier($metadata->tableName),
            implode(",\n    ", $columns),
        );

        $this->connection->execute($sql);
    }

    private function columnDefinition(EntityMetadata $metadata, PropertyMapping $mapping, string $driver): string
    {
        $column = $this->connection->quoteIdentifier($mapping->columnName);

        if ($mapping->id && $mapping->generated) {
            return sprintf('%s %s', $column, $this->generatedIdDefinition($metadata, $mapping, $driver));
        }

        $definition = sprintf('%s %s', $column, $this->databaseType($metadata, $mapping, $driver));

        if ($mapping->id) {
            return $definition . ' PRIMARY KEY';
        }

        return $mapping->nullable ? $definition : $definition . ' NOT NULL';
    }

    private function generatedIdDefinition(EntityMetadata $metadata, PropertyMapping $mapping, string $driver): string
    {
        $type = $mapping->property->getType();

        if (!$type instanceof ReflectionNamedType || $type->getName() !== 'int') {
            throw new MappingException(sprintf(
                'Generated id property "%s::$%s" must have type int.',
                $metadata->className,
                $mapping->propertyName,
            ));
        }

        return match ($driver) {
            'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
            'mysql' => 'BIGINT AUTO_INCREMENT PRIMARY KEY',
            'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            default => throw new SumireException(sprintf('Schema creation is not supported for PDO driver "%s".', $driver)),
        };
    }

    private function databaseType(EntityMetadata $metadata, PropertyMapping $mapping, string $driver): string
    {
        if ($mapping->type === ColumnType::Json) {
            return match ($driver) {
                'mysql' => 'JSON',
                'pgsql' => 'JSONB',
                default => 'TEXT',
            };
        }

        if ($mapping->type === ColumnType::DateTime) {
            return $this->dateTimeType($driver);
        }

        $type = $mapping->property->getType();
        if (!$type instanceof ReflectionNamedType) {
            throw $this->unsupportedType($metadata, $mapping);
        }

        $typeName = $type->getName();
        if ($type->isBuiltin()) {
            return $this->scalarType($metadata, $mapping, $typeName, $driver);
        }

        if ($typeName === DateTimeInterface::class || is_subclass_of($typeName, DateTimeInterface::class)) {
            return $this->dateTimeType($driver);
        }

        if (enum_exists($typeName)) {
            if (!is_subclass_of($typeName, BackedEnum::class)) {
                throw $this->unsupportedType($metadata, $mapping);
            }

            $backingType = (new ReflectionEnum($typeName))->getBackingType();
            if (!$backingType instanceof ReflectionNamedType) {
                throw $this->unsupportedType($metadata, $mapping);
            }

            return $this->scalarType($metadata, $mapping, $backingType->getName(), $driver);
        }

        throw $this->unsupportedType($metadata, $mapping);
    }

    private function scalarType(
        EntityMetadata $metadata,
        PropertyMapping $mapping,
        string $type,
        string $driver,
    ): string {
        return match ($type) {
            'string' => $driver === 'sqlite' ? 'TEXT' : 'VARCHAR(255)',
            'int' => $driver === 'sqlite' ? 'INTEGER' : 'BIGINT',
            'float' => match ($driver) {
                'sqlite' => 'REAL',
                'mysql' => 'DOUBLE',
                default => 'DOUBLE PRECISION',
            },
            'bool' => $driver === 'sqlite' ? 'INTEGER' : 'BOOLEAN',
            default => throw $this->unsupportedType($metadata, $mapping),
        };
    }

    private function dateTimeType(string $driver): string
    {
        return match ($driver) {
            'sqlite' => 'TEXT',
            'mysql' => 'DATETIME',
            default => 'TIMESTAMP WITHOUT TIME ZONE',
        };
    }

    private function unsupportedType(EntityMetadata $metadata, PropertyMapping $mapping): MappingException
    {
        return new MappingException(sprintf(
            'Cannot infer a database type for property "%s::$%s".',
            $metadata->className,
            $mapping->propertyName,
        ));
    }

    private function assertSupportedDriver(string $driver): void
    {
        if (!in_array($driver, ['sqlite', 'mysql', 'pgsql'], true)) {
            throw new SumireException(sprintf('Schema creation is not supported for PDO driver "%s".', $driver));
        }
    }
}
